Update ci-push-feature-branch.yaml

diff --git a/.github/workflows/ci-push-feature-branch.yaml b/.github/workflows/ci-push-feature-branch.yaml
--- a/.github/workflows/ci-push-feature-branch.yaml
+++ b/.github/workflows/ci-push-feature-branch.yaml
@@ -1,7 +1,6 @@
-name: CI feature/** branch
+name: Push (feature/** branch)
 
 on:
-  # workflow_dispatch:
   push:
     branches: ['feature/**']
 
@@ -11,9 +10,9 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [ '22.x' ]      # NodeJS version   | Use this to test new NodeJS versions
-        mongodb-version: [ '8.0' ]    # MongoDB version  | Use this to test new MongoDB versions
-      max-parallel: 1                 # The maximum number of jobs run in parallel
+        node-version: [ '22.x' ]             # NodeJS version   | Use this to test new NodeJS versions
+        mongodb-version: [ '7.0', '8.0' ]    # MongoDB version  | Use this to test new MongoDB versions
+      max-parallel: 1                        # The maximum number of jobs run in parallel
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -54,11 +53,18 @@ jobs:
       
       - name: Install dependencies
         run: npm install
-#        run: npm ci 				# Install dependencies from package-lock.json
+       # run: npm ci                     # TO-DO: Install dependencies from package-lock.json
+      
+      # - name: Run ESLint               # TO-DO: add linter check
+      #   run: npm run lint
 
       - name: Run tests
-        # run: npm test -- src/test/unit/cron-jobs/checkForLastLogin.spec.js --verbose --coverage=false 2>&1 | tee full-tests.log | tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > tests-results.txt) || true
-        run: npm test --verbose --coverage=false 2>&1 | tee full-tests.log | tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > tests-results.txt) || true
+        run: |
+          npm test -- src/test/unit/cron-jobs/checkForLastLogin.spec.js --verbose --coverage=false 2>&1 | \
+          # npm test --verbose --coverage=false 2>&1 | \
+          tee "full-tests-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" | \
+          tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > \
+          "tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.txt") || true
         env:
           NODE_OPTIONS: --max_old_space_size=4096
           MONGODB_URL: mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASS }}@localhost:27017/${{ secrets.MONGODB_DB }}?authSource=admin
@@ -87,31 +93,58 @@ jobs:
 
       - name: Extract Errors
         run: |
-          awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' full-tests.log > test-errors.log || true
-
-      - name: Generate Report
-        run: |
-          echo '### ✅ CI Report' >> $GITHUB_STEP_SUMMARY
-          echo '' >> $GITHUB_STEP_SUMMARY
-          echo '**🔹 Node.js Version:** ${{ matrix.node-version }}' >> $GITHUB_STEP_SUMMARY
-          echo '**🔹 MongoDB Version:** ${{ matrix.mongodb-version }}' >> $GITHUB_STEP_SUMMARY
-          echo '' >> $GITHUB_STEP_SUMMARY
-          
-          echo '### 🧪 Test Results' >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
-          cat tests-results.txt >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
-          echo '' >> $GITHUB_STEP_SUMMARY
-
-          if [[ -s test-errors.log ]]; then
-            echo '### ❌ Test Errors' >> $GITHUB_STEP_SUMMARY
-            echo '```' >> $GITHUB_STEP_SUMMARY
-            cat test-errors.log >> $GITHUB_STEP_SUMMARY
-            echo '```' >> $GITHUB_STEP_SUMMARY
-          fi
-
-      - name: Upload Test Logs
+          awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' \
+          "full-tests-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" > \
+          "test-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" || true
+      
+      - name: Upload Test Results
         uses: actions/upload-artifact@v4
         with:
-          name: tests-log
-          path: full-tests.log
+          name: tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}
+          path: |
+            tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.txt
+            test-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log
+  
+  generate-report:
+    name: Generate Test Report
+    runs-on: ubuntu-latest
+    needs: run-tests  
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Download All Test Results
+        uses: actions/download-artifact@v4
+        with:
+          path: test-reports
+
+      - name: Generate Test Report
+        run: |
+          CI_MARKER="### ✅ CI Report - $(TZ="Europe/Kyiv" date +"%H:%M %d/%m/%Y")"
+          echo "$CI_MARKER" > test-report.txt
+          echo "" >> test-report.txt
+          for folder in test-reports/tests-results-*; do
+            TEST_VERSION=$(basename "$folder")
+            NODE_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f3)
+            MONGO_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f4)
+            TEST_FILE="$folder/tests-results-$NODE_VERSION-$MONGO_VERSION.txt"
+            ERRORS_FILE="$folder/test-errors-$NODE_VERSION-$MONGO_VERSION.log"
+            echo "**🔹 Node.js Version:** $NODE_VERSION" >> test-report.txt
+            echo "**🔹 MongoDB Version:** $MONGO_VERSION" >> test-report.txt
+            echo "" >> test-report.txt
+            echo "### 🧪 Test Results" >> test-report.txt
+            echo '```' >> test-report.txt
+            cat "$TEST_FILE" >> test-report.txt
+            echo '```' >> test-report.txt
+            echo "" >> test-report.txt
+            if [[ -s "$ERRORS_FILE" ]]; then
+              echo "### ❌ Test Errors" >> test-report.txt
+              echo '```' >> test-report.txt
+              cat "$ERRORS_FILE" >> test-report.txt
+              echo '```' >> test-report.txt
+            fi
+            echo "" >> test-report.txt
+          done
+      
+      - name: Publish Report in GitHub Actions Summary
+        run: cat test-report.txt >> $GITHUB_STEP_SUMMARY
